<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" xmlns:umln50kartdata="https://skjema.geonorge.no/SOSI/produktspesifikasjon/n50-kartdata/uml-n50-kartdata/1.0" elementFormDefault="qualified" targetNamespace="https://skjema.geonorge.no/SOSI/produktspesifikasjon/n50-kartdata/uml-n50-kartdata/1.0" version="1.0">
  <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo" schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element name="KantUtsnitt" substitutionGroup="umln50kartdata:SOSI_Objekt_Hjelpelinjer" type="umln50kartdata:KantUtsnittType">
    <annotation>
      <documentation>avgrensning av et utsnitt</documentation>
    </annotation>
  </element>
  <complexType name="KantUtsnittType">
    <complexContent>
      <extension base="umln50kartdata:SOSI_Objekt_HjelpelinjerType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <documentation>forløp som følger overgang mellom ulike fenomener</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="KantUtsnittPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:KantUtsnitt"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="MålemetodeType">
    <annotation>
      <documentation>metode som ligger til grunn for registrering av posisjon


-- Definition - -
method on which registration of position is based</documentation>
    </annotation>
    <union memberTypes="umln50kartdata:MålemetodeEnumerationType umln50kartdata:MålemetodeOtherType"/>
  </simpleType>
  <simpleType name="MålemetodeEnumerationType">
    <annotation>
      <documentation>metode som ligger til grunn for registrering av posisjon


-- Definition - -
method on which registration of position is based</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="Terrengmålt: Uspesifisert måleinstrument">
        <annotation>
          <documentation>Målt i terrenget , uspesifisert metode/måleinstrument</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Terrengmålt: Totalstasjon">
        <annotation>
          <documentation>Målt i terrenget med totalstasjon</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Terrengmålt: Teodolitt og el avstandsmåler">
        <annotation>
          <documentation>Målt i terrenget med teodolitt og elektronisk avstandsmåler</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Terrengmålt: Teodolitt og målebånd">
        <annotation>
          <documentation>Målt i terrenget med teodolitt og målebånd</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Terrengmålt: Ortogonalmetoden">
        <annotation>
          <documentation>Målt i terrenget, ortogonalmetoden</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Utmål">
        <annotation>
          <documentation>Punkt beregnet på bakgrunn av måling mot andre punkter, slik som to avstander eller avstand og retning

-- Definition --
Point calculated on the basis of other items, such as two distances or distance + direction.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Tatt fra plan">
        <annotation>
          <documentation>Tatt fra plan eller godkjent tiltak</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Annet  (denne har ingen mening, bør fjernes?)">
        <annotation>
          <documentation>Annet</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Stereoinstrument">
        <annotation>
          <documentation>Målt i stereoinstrument, uspesifisert instrument</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Aerotriangulert">
        <annotation>
          <documentation>Punkt beregnet ved aerotriangulering

-- Definition --
Point calculated by aerotriangulation</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Stereoinstrument: Analytisk plotter">
        <annotation>
          <documentation>Målt i stereoinstrument, analytisk plotter</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Stereoinstrument: Autograf">
        <annotation>
          <documentation>Målt i stereoinstrument, autograf, analogt instrument</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Stereoinstrument: Digitalt">
        <annotation>
          <documentation>Målt i stereoinstrument, digitalt instrument</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Scannet fra kart">
        <annotation>
          <documentation>Geometri overført fra kart maskinelt ved hjelp av skanner, uspesifisert kartmedium</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Skannet fra kart: Blyantoriginal">
        <annotation>
          <documentation>Geometri overført fra kart maskinelt ved hjelp av skanner. Kartmedium er blyantoriginal</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Skannet fra kart: Rissefolie">
        <annotation>
          <documentation>Geometri overført fra kart maskinelt ved hjelp av skanner. Kartmedium er rissefolie</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Skannet fra kart: Transparent folie, god kvalitet">
        <annotation>
          <documentation>Geometri overført fra kart maskinelt ved hjelp av skanner. Kartmedium er transparent folie av  god kvalitet.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Skannet fra kart: Transparent foile, mindre god kvalitet">
        <annotation>
          <documentation>Geometri overført fra kart maskinelt ved hjelp av skanner. Kartmedium er tranparent foile av mindre god kvalitet</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Skannet fra kart: Papirkopi">
        <annotation>
          <documentation>Geometri overført fra kart maskinelt ved hjelp av skanner. Kartmedium er papirkopi.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Flybåren laserscanner">
        <annotation>
          <documentation>Målt med laserskanner fra fly</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Bilbåren laser">
        <annotation>
          <documentation>Målt med laserskanner plassert i kjøretøy</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Lineær referanse">
        <annotation>
          <documentation>brukes for objekter som er stedfestet med lineær referanse, enten disse leveres med stedfesting kun som lineære referanser, eller med koordinatgeometri avledet fra lineære referanser</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringbord: Ortofoto eller flybilde">
        <annotation>
          <documentation>Geometri overført fra ortofoto eller flybilde ved hjelp av manuell registrering på et digitaliseringsbord, uspesifisert bildemedium</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringbord: Ortofoto, film">
        <annotation>
          <documentation>Geometri overført fra ortofoto ved hjelp av manuell registrering på et digitaliseringsbord. Bildemedium er film</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringbord: Ortofoto, fotokopi">
        <annotation>
          <documentation>Geometri overført fra ortofoto ved hjelp av manuell registrering på et digitaliseringsbord. Bildemedium er fotokopi</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringbord: Flybilde, film">
        <annotation>
          <documentation>Geometri overført fra flybilde ved hjelp av manuell registrering på et digitaliseringsbord. Bildemedium er film</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringbord: Flybilde, fotokopi">
        <annotation>
          <documentation>Geometri overført fra flybilde ved hjelp av manuell registrering på et digitaliseringsbord. Bildemedium er fotokopi</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitalisert på skjerm fra ortofoto">
        <annotation>
          <documentation>Geometri overført fra ortofoto ved hjelp av manuell registrering på skjerm</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitalisert på skjerm fra satelittbilde">
        <annotation>
          <documentation>Geometri overført fra satelittbilde ved hjelp av manuell registrering på skjerm</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitalisert på skjerm fra andre digitale rasterdata"/>
      <enumeration value="Digitalisert på skjerm fra tolkning av seismikk"/>
      <enumeration value="Vektorisering av laserdata">
        <annotation>
          <documentation>Vektorisering fra laserdata, brukes også der vektoriseringen støttes av ortofoto</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringsbord: Kart">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på et digitaliseringsbord, medium uspesifisert</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringsbord: Kart, blyantoriginal">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på et digitaliseringsbord. Kartmedium er blyantoriginal</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringsbord: Kart, rissefoile">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på et digitaliseringsbord. Kartmedium er rissefolie</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringsbord: Kart, transparent foile, god kvalitet">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på et digitaliseringsbord. Kartmedium er transparent folie av god kvalitet, samkopi</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringsbord: Kart, transparent foile, mindre god kvalitet">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på et digitaliseringsbord. Kartmedium er transparent folie av mindre god kvalitet, samkopi</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitaliseringsbord: Kart, papirkopi">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på et digitaliseringsbord. Kartmedium er papirkopi</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Digitalisert på skjerm fra skannet kart">
        <annotation>
          <documentation>Geometri overført fra kart ved hjelp av manuell registrering på skjerm, medium skannet kart (raster), samkopi</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Genererte data (interpolasjon)">
        <annotation>
          <documentation>Genererte data, interpolasjonsmetode. Ikke nærmere spesifisert</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Genererte data (interpolasjon): Terrengmodell">
        <annotation>
          <documentation>Genererte data, interpolasjonsmetode, fra terrengmodell</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Genererte data (interpolasjon): Vektet middel">
        <annotation>
          <documentation>Genererte data, interpolasjonsmetode, vektet middel</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Genererte data: Fra annen geometri">
        <annotation>
          <documentation>Genererte data: Sirkelgeometri, korridor eller annen geometri generert ut fra f.eks et punkt eller en linje (f.eks midtlinje veg)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Genererte data: Generalisering"/>
      <enumeration value="Genererte data: Sentralpunkt"/>
      <enumeration value="Genererte data: Sammenknytningspunkt, randpunkt">
        <annotation>
          <documentation>Genererte data: Sammenknytningspunkt (f.eks mellom ulike kartlegginger), randpunkt (f.eks mellom ulike kilder til kart)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Koordinater hentet fra GAB">
        <annotation>
          <documentation>Koordinater hentet fra GAB, forløperen til registerdelen av matrikkelen</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Koordinater hentet fra JREG">
        <annotation>
          <documentation>Koordinater hentet fra JREG, jordregisteret</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Beregnet">
        <annotation>
          <documentation>Beregnet, uspesifisert hvordan</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Spesielle metoder">
        <annotation>
          <documentation>Spesielle metoder, uspesifisert</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Spesielle metoder: Målt med stikkstang"/>
      <enumeration value="Spesielle metoder: Målt med waterstang"/>
      <enumeration value="Spesielle metoder: Målt med målehjul"/>
      <enumeration value="Spesielle metoder: Målt med stigningsmåler"/>
      <enumeration value="Fastsatt punkt">
        <annotation>
          <documentation>Punkt fastsatt ut fra et grunnlag (kart, bilde), f.eks ved partenes enighet ved en oppmålingsforretning</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Fastsatt ved dom eller kongelig resolusjon">
        <annotation>
          <documentation>Geometri fastsatt ved dom, lov, traktat eller kongelig resolusjon</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Annet (spesifiseres i filhode) ( bør vel fjernes, blir borte ved overføring mellom systemer)">
        <annotation>
          <documentation>Annet (spesifiseres i filhode)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Frihåndstegning">
        <annotation>
          <documentation>Digitalisert ut fra frihåndstegning.  Frihåndstegning er basert på svært grovt grunnlag eller ikke noe grunnlag</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Frihåndstegning på kart">
        <annotation>
          <documentation>Digitalisert fra krokering på kart, dvs grovt skissert på kart</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Frihåndstegning på skjerm">
        <annotation>
          <documentation>Digitalisert ut fra frihåndstegning (direkte på skjerm). Frihåndstegning er basert på svært grovt grunnlag eller ikke noe grunnlag</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Treghetsstedfesting"/>
      <enumeration value="GNSS: Kodemåling, relative målinger">
        <annotation>
          <documentation>Innmålt med satellittbaserte systemer for navigasjon og posisjonering med global dekning (f.eks GPS, GLONASS, GALILEO): Kodemåling, relative målinger.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="GNSS: Kodemåling, enkle målinger">
        <annotation>
          <documentation>Innmålt med satellittbaserte systemer for navigasjon og posisjonering med global dekning (f.eks GPS, GLONASS, GALILEO): Kodemåling, enkle målinger.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="GNSS: Fasemåling, statisk måling">
        <annotation>
          <documentation>Innmålt med satellittbaserte systemer for navigasjon og posisjonering med global dekning (f.eks GPS, GLONASS, GALILEO): Fasemåling statisk måling.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="GNSS: Fasemåling, andre metoder">
        <annotation>
          <documentation>Innmålt med satellittbaserte systemer for navigasjon og posisjonering med global dekning (f.eks GPS, GLONASS, GALILEO): Fasemåling andre metoder.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Kombinasjon av GNSS/Treghet">
        <annotation>
          <documentation>Kombinasjon av GPS/Treghet</documentation>
        </annotation>
      </enumeration>
      <enumeration value="GNSS: Fasemåling RTK">
        <annotation>
          <documentation>Innmålt med satellittbaserte systemer for navigasjon og posisjonering med global dekning (f.eks GPS, GLONASS, GALILEO).: Fasemåling RTK (realtids kinematisk måling)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="GNSS: Fasemåling , float-løsning">
        <annotation>
          <documentation>Innmålt med satellittbaserte systemer for navigasjon og posisjonering med global dekning (f.eks GPS, GLONASS, GALILEO). Fasemåling float-løsning</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Ukjent målemetode">
        <annotation>
          <documentation>Målemetode er ukjent</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="MålemetodeOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="Posisjonskvalitet" substitutionGroup="gml:AbstractObject" type="umln50kartdata:PosisjonskvalitetType"/>
  <complexType name="PosisjonskvalitetType">
    <sequence>
      <element name="målemetode" type="umln50kartdata:MålemetodeType">
        <annotation>
          <documentation>metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss</documentation>
        </annotation>
      </element>
      <element name="nøyaktighet" type="gml:CodeType">
        <annotation>
          <documentation>punktstandardavviket i grunnriss for punkter samt tverravvik for linjer

Merknad:
Oppgitt i cm</documentation>
          <appinfo>
            <sc:targetCodeListURI>http://skjema.geonorge.no/legg_inn_riktig_url</sc:targetCodeListURI>
            <sc:taggedValue tag="SOSI_navn">NØYAKTIGHET</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="PosisjonskvalitetPropertyType">
    <sequence>
      <element ref="umln50kartdata:Posisjonskvalitet"/>
    </sequence>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_Flater" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_FlaterType">
    <annotation>
      <documentation>abstrakt supertype som samler fellesegenskaper og assosiasjoner som gjelder objekttyper som bare har flategeometri</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_FlaterType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="kantUtsnitt" type="umln50kartdata:KantUtsnittPropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_FlaterPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_Flater"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_Hjelpelinjer" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_HjelpelinjerType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er til felles for KantUtsnitt, Dataavgrensning og FiktivDelelinje i dette applikasjonsskjemaet</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_HjelpelinjerType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_HjelpelinjerPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_Hjelpelinjer"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_Kombinasjon_Ulike_Geometrityper" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_Kombinasjon_Ulike_GeometrityperType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er til felles for alle objekttyper med en kombinasjon av punkt- og flategeometri eller linje- og flategeometri i dette applikasjonsskjemaet</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_Kombinasjon_Ulike_GeometrityperType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="datafangstdato" type="date">
            <annotation>
              <documentation>dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra Oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">DATAFANGSTDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="kvalitet" type="umln50kartdata:PosisjonskvalitetPropertyType">
            <annotation>
              <documentation>beskrivelse av kvaliteten på stedfestingen

Merknad: Denne er identisk med ..KVALITET i tidligere versjoner av SOSI.</documentation>
            </annotation>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="kantUtsnitt" type="umln50kartdata:KantUtsnittPropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_Kombinasjon_Ulike_GeometrityperPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_Kombinasjon_Ulike_Geometrityper"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_Linjer_Samferdsel" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_Linjer_SamferdselType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er til felles for flere objekttyper i underpakke Samferdsel i dette applikasjonsskjemaet</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_Linjer_SamferdselType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="medium">
            <annotation>
              <documentation>objektets beliggenhet i forhold til jordoverflaten

Eksempel:
På bro, i tunnel, inne i et bygningsmessig anlegg, etc.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">MEDIUM</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="datafangstdato" type="date">
            <annotation>
              <documentation>dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra Oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">DATAFANGSTDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kvalitet" type="umln50kartdata:PosisjonskvalitetPropertyType">
            <annotation>
              <documentation>beskrivelse av kvaliteten på stedfestingen

Merknad: Denne er identisk med ..KVALITET i tidligere versjoner av SOSI.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KVALITET</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_Linjer_SamferdselPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_Linjer_Samferdsel"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_PunkterOgLinjer" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_PunkterOgLinjerType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er til felles for flere objekttyper med punkt- eller linjegeometri i underpakkene Administrative områder, Arealdekke, Bygninger og anlegg, Restriksjonsområder og Samferdsel i dette applikasjonsskjemaet</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_PunkterOgLinjerType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="datafangstdato" type="date">
            <annotation>
              <documentation>dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra Oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">DATAFANGSTDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kvalitet" type="umln50kartdata:PosisjonskvalitetPropertyType">
            <annotation>
              <documentation>beskrivelse av kvaliteten på stedfestingen

Merknad: Denne er identisk med ..KVALITET i tidligere versjoner av SOSI.</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_PunkterOgLinjerPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_PunkterOgLinjer"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_PunkterOgLinjer_Høyde" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_PunkterOgLinjer_HøydeType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er til felles for flere objekttyper i underpakke Høyde i dette applikasjonsskjemaet</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_PunkterOgLinjer_HøydeType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="medium">
            <annotation>
              <documentation>objektets beliggenhet i forhold til jordoverflaten

Eksempel:
På bro, i tunnel, inne i et bygningsmessig anlegg, etc.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">MEDIUM</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="datafangstdato" type="date">
            <annotation>
              <documentation>dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra Oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">DATAFANGSTDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kvalitet" type="umln50kartdata:PosisjonskvalitetPropertyType">
            <annotation>
              <documentation>beskrivelse av kvaliteten på stedfestingen

Merknad: Denne er identisk med ..KVALITET i tidligere versjoner av SOSI.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KVALITET</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_PunkterOgLinjer_HøydePropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_PunkterOgLinjer_Høyde"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SOSI_Objekt_Sperrelinjer" substitutionGroup="gml:AbstractFeature" type="umln50kartdata:SOSI_Objekt_SperrelinjerType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er felles for alle sperrelinjer i dette applikasjonsskjemaet</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SOSI_Objekt_SperrelinjerType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektdataene</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SOSI_Objekt_SperrelinjerPropertyType">
    <sequence minOccurs="0">
      <element ref="umln50kartdata:SOSI_Objekt_Sperrelinjer"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
</schema>
